### ISSUE TITLE
where is the documentation, miss a design

### ISSUE THREAD

**Issue by DanielRuf** [iRail/The-DataTank#125]
Have PHP 5.3.10 here
I am working on a local webserver
After the installation is complete I am always redirected from index.php to /installer

Seems for me there are many things missing like the UI / design?

**Comment by coreation** [comment]
Hej Daniel,

Currently we only have an installer to guide you through the installation process. This means that indeed the index.php will guide you to the installer, and if everything is ok it will state that you have installed your datatank correctly. We don't have a UI integrated just yet, we can tell you though that one has been made in drupal as a side project that allows you to create and manage resources from a drupal UI interface. We'll notify when and where you can use this tool as soon as we know something :).

**Comment by DanielRuf** [comment]
Sounds great, thanks =)

**Comment by coreation** [comment]
You're very weclome :)

**Comment by lievenjanssen** [comment]
Daniel,

can you let me know what the specific use case is you want to use The DataTank for? You can drop me an email at lieven@thedatatank.com

Best Regards,

Lieven

**Comment by coreation** [comment]
Hi Daniel,

We performed a fix for issue #129 which was causing parameters passed to installed resources unreachable in the installed resource itself. This is fixed now. So if you're working with installed resources, you might want to download the new zip/tar.gz and overwrite your current DataTank file structure. Your config file should be a-ok and your resources should work as well since they're stored in the database and are completely separated from the code :).

Best regards,

Jan

**Comment by DanielRuf** [comment]
Issue 129?
Also I had no problem with installed ressources and so on.

**Comment by coreation** [comment]
Oops, sorry a tiny typo there, that should be issue #126. It's about passing requiredparameters to the installed resources where they can be address by as $this->requiredparametername. So if you experience this problem, that should be fixed with the latest update :).
