### ISSUE TITLE
Support tagging for resources

### ISSUE THREAD

**Issue by lievenjanssen** [iRail/The-DataTank#13]
Add an extra tags parameter to resources:
- generic resource: can be defined through REST API
- remote resource: use the remote tags parameter?
- installed resource: can be defined in resource itself

You need to create a new table Tags in the data model (1-\* relationship with resource)

Value for tag param in rest call could be: 'Sociale Dienst, Analyse, Werkloosheid'

**Comment by coreation** [comment]
I think you mean a *-1 relation with resource ;). Anyway how i see it, we might also forsee a "link" value in the tags table, so the "pretty" name like Analyse can be linked with an ontology that specifies the name itself more, this might end up ( in a later stage) in a combined unique key, because maybe there will be more types of "Analyse" later on.

In the early stage:

Extra table tags, with id | name | link and a aggregation table called resource_tags with id | resource_id | tag_id This way the implementation will be more normalized and future changes will have minimal impact on the back-end.

**Comment by coreation** [comment]
You can now add tags to resources, if a resource is deleted it's entry will be deleted out of the coupling table as well. A follow up issue or more like a feature would be on 
1) how to show these tags
2) how will we further implemente an update action ( this is rather messy, because it's not a "1 way drive like a creation or deletion" )
3) how do we delete and manage tags aside from resources? Provide an installed resource Tags who can manage these ?

**Comment by coreation** [comment]
This implementation is now rolled back. The update mechanism has found its true purpose, see issue #48
