### ISSUE TITLE
URL field too short in database

### ISSUE THREAD

**Issue by pietercolpaert** [iRail/The-DataTank#137]
When trying to put a CSV resource with this URL:

http://nl.dbpedia.org/sparql?default-graph-uri=http%3A%2F%2Fnl.dbpedia.org&query=select+%3Flabel%2C+fn%3Aconcat%28%3Flatdeg%2C%22.%22%2C%3Flatmin+*+1000%2F6+%2B+%3Flatsec+*+10%2F6%29+as+%3Flat%2Cfn%3Aconcat%28%3Flongdeg%2C%22.%22%2C%3Flongmin+*+1000%2F6+%2B+%3Flongsec+*+10%2F6%29+as+%3Flong%0D%0Awhere+%7B%0D%0A+%3Fstation+prop-nl%3Astationscode+%3Fcode+.%0D%0A+%3Fstation+rdfs%3Alabel+%3Flabel+.%0D%0A+%3Fstation+dbpedia-owl%3Aabstract+%3Fabstract+.%0D%0A+%3Fstation+prop-nl%3AlatDeg+%3Flatdeg+.%0D%0A+%3Fstation+prop-nl%3AlatMin+%3Flatmin+.%0D%0A+%3Fstation+prop-nl%3AlatSec+%3Flatsec+.%0D%0A+%3Fstation+prop-nl%3AlonDeg+%3Flongdeg+.%0D%0A+%3Fstation+prop-nl%3AlonMin+%3Flongmin+.%0D%0A+%3Fstation+prop-nl%3AlonSec+%3Flongsec+.%0D%0A%7D&format=csv&timeout=0&debug=on

It doesn't return an error. Instead it just adds a URL that is cut somewhere in the middle and never shows anything at all.

**Comment by coreation** [comment]
Hi pieter,

I solved the problem, in order to make it as easy for users I had to update the version so that a back-end update will trigger. It contains a modification of the length of the column. Other strategies shouldn't experience this issue as they are created by the DBAL, and this will handle that sort of things.

Another point that I have discovered is that my first attempt to re-create this error I had a time-out. Which resulted in a non-complete definition a the resource. These time-outs are fatal errors and cannot be handled. Perhaps later on a transition towards a DBAL with transactions should provide a clean solution.
