### ISSUE TITLE
Titles for resources

### ISSUE THREAD

**Issue by coreation** [iRail/The-DataTank#35]
There was a request for providing a title ( sort of alias ) for resources and packages. Not sure if it's meant to provide an alias for  a package, and an alias for a resource name, wasn't that clear in the request. I'll presume it's both as that makes more sense. This gives us the opportunity to provide neat names instead of taking the given resource and package name, who are sometimes just concatenated descriptions.

**Comment by lievenjanssen** [comment]
This is indeed for both:
- for resources:
  title should be an optional parameter when you create a new resource (if not provided it takes the resource url name)
- for packages

you should be able to do a put request to a package e.g. http://tdtinstance/package with a title parameter for the package name (by default this will probably not be provided because we automatically create a package when we do a PUT to a resource if it's not provided it should take the package url name)

Later on a REST call can be made to update the title of the package.

**Comment by coreation** [comment]
And where should does info appear ? Should package_title appear in the /Packages ? and resource_title in /Resources ? Or do we create an entire new info resource ( ResourceDetail ) ?

**Comment by coreation** [comment]
The representation of the new details are to be issued in another issue, added package and resource title possibilities
