### ISSUE TITLE
DCMI Metadata Terms

### ISSUE THREAD

**Issue by lievenjanssen** [iRail/The-DataTank#36]
Implement the Dublin Core Metadata Initiative terms as default properties for a resource:

abstract, accessRights, accrualMethod, accrualPeriodicity, accrualPolicy, alternative, audience, available, bibliographicCitation, conformsTo, contributor, coverage, created, creator, date, dateAccepted, dateCopyrighted, dateSubmitted, description, educationLevel, extent, format, hasFormat, hasPart, hasVersion, identifier, instructionalMethod, isFormatOf, isPartOf, isReferencedBy, isReplacedBy, isRequiredBy, issued, isVersionOf, language, license, mediator, medium, modified, provenance, publisher, references, relation, replaces, requires, rights, rightsHolder, source, spatial, subject, tableOfContents, temporal, title, type, valid

(some of them can be implented automatically or are already implemented)

I don't think that all need to be implemented,  but we need to review each one of them.

More information see: http://dublincore.org/documents/dcmi-terms/

**Comment by coreation** [comment]
So these properties are all meta-data, ...so POST requests meant as an update should update the resource with the meta data... So this could be seen as another table holding all of these properties (I'd like to implement it, but still keep it as apart from our core back-end as possible so that we can unplug it when something else, more popular, pops up), mapped on resource id's... ?

**Comment by coreation** [comment]
I still think we need to be as "light" as possible, the meta-data described here are indeed mostly usefull, and some of them are already present in TDT, but I think every addition of a piece of meta-data should be discussed first. We don't want to overload our users with a load of options and features. If we decide to go with an update mechanism ( because the addition of meta-data terms will use this ) We have to brainstorm first on how we do this as correctly as possible.

**Comment by coreation** [comment]
Implemented a set of the DCMI metadata. Some were not entirely relevant or totally not relevant on our framework. This is ofcourse discussable and is in context of what we're planning towards the future.

**Comment by coreation** [comment]
As stated in the last comment, most important and relevant ones are included, you can add them with an initial put request or change them with a PATCH requests.
