### ISSUE TITLE
XLS resource

### ISSUE THREAD

**Issue by coreation** [iRail/The-DataTank#42]
If an Excel resource is included in a zip or tar ( made by a tag i.e. ) Then any addition ( even a CSV resource ) will trigger an error because XLS resource cannot find the library, I think this had something to do with the constructor of the XLS resource ( Do i recall this correctly Lieven ? )

**Comment by pietercolpaert** [comment]
2 ways to fix this:
- Don't include all generic resources by default, develop these separately on a We Open Data github organization
- Include this but add autoloading (http://php.net/manual/en/function.spl-autoload-register.php) instead of includes and throw an exception when doing an XLS call when the excel lib is not set.

This is again the debate we have to do:
- Micro-architecture
- Monolithic architecture

We need to discuss this asap.

**Comment by coreation** [comment]
Fixed for now, the outcome of the constructor was still an error if none XLS library was passed. I moved the validation of the path to the isValid function which is called in every create call.

**Comment by coreation** [comment]
Also what do you mean by monolithic architecture ? I think our way of developing is in no way monolithic as the definition of it in software context being that the software is completely interwoven with eachother and functionalities aren't pluggable.

**Comment by coreation** [comment]
I'm going to close this issue, I think the auto-load should be integrated in TDT ( not really related solely on TDT )
