### ISSUE TITLE
Hierarchische package-structuur

### ISSUE THREAD

**Issue by coreation** [iRail/The-DataTank#46]
Packages should be able to represent a hierarchical structure, also in a latter stage delete /..../.../\* i.e. should delete all underlying structures.

**Comment by pietercolpaert** [comment]
I personally would rather see the package structure removed as this will give a much cleaner code base. Why did you decide on supporting this rather than removing packages?

Why I want it to be removed:
- Will be a lot easier to support multi-sites and one click new TDT set-up
- We don't want to be able to categorize datasets, this is something CKAN should do
- When all resources are flat, it's easier to semantify them

For instance:
data.irail.be would exist out of a couple of datatanks in several subdirs: NMBS, MIVB, DL, Parkings... Each of these subdirs are just different configurationfiles on one installation (cfr. Drupal).

**Comment by marc-portier** [comment]
Why not mix and match?

The package concept can be removed imho, and TDT should be agnostic of any structure in the resource-names 
So rather then saying these URIs should be flat I would argument that TDT just handles these names in an opaque manner.

In other words: these URIs (just strings then) could still contain / characters in them allowing anyone to assign meaning or use to the implicitly created path-segments.

I find it practical to organize my URI's this way. (and limiting that the current Package only goes one level deep)

Maybe in the future we could even think about bulk management operations (DELETE, MOVE?) that are hooking in with these implicit parent-path-structures.

Other future hooks on these implicit path-segments might allow to control access too.

**Comment by pietercolpaert** [comment]
I agree! This is already possible by using the $RESTparameters and $requiredparameters array. If we clean up this usage of parameters, we're good I believe.

**Comment by coreation** [comment]
I was thinking about this as well, but by cleaning up, you make it sound so easy. I have learned to not speak about "oh that's easy" until I actually start coding the thing. But making packages agnostic is a good thing: let the owner or user give meaning to it, instead of limiting it to our specs.

**Comment by coreation** [comment]
-- deleted comment --

**Comment by coreation** [comment]
A quick rework has been done, hierchical packages are supported now.

BUT:

We're going to have to split the /Ontology -CUD operations (which isn't that hard).
In order to enjoy the full potential of the hier. structure in an efficient way, we're going to have to do a major update on the back-end where packages can link back to packages (so package has a FK to it's own table). That way we can easily do deletes on entire packages and subpackages and report packages under packages without having to perform a (imho) very expensive lookup with a regex (where package_name STARTS WITH 'package to search' i.e.).

**Comment by coreation** [comment]
No commit messages have been logged with the last commits to this issue, I suggest taking a look at the hierarchical_package brach.
