### ISSUE TITLE
URI vs URL parameter battle

### ISSUE THREAD

**Issue by coreation** [iRail/The-DataTank#55]
Which one will we use consistently throughout the resources ?

**Comment by marc-portier** [comment]
I vote for URI

**Comment by lievenjanssen** [comment]
No voting needed, following the definition in this article it should be URL:

http://ajaxian.com/archives/uri-vs-url-whats-the-difference

or

http://www.ietf.org/rfc/rfc2396.txt chapter 1.2

   A URI can be further classified as a locator, a name, or both.  The
   term "Uniform Resource Locator" (URL) refers to the subset of URI
   that identify resources via a representation of their primary access
   mechanism (e.g., their network "location"), rather than identifying
   the resource by name or by some other attribute(s) of that resource.
   The term "Uniform Resource Name" (URN) refers to the subset of URI
   that are required to remain globally unique and persistent even when
   the resource ceases to exist or becomes unavailable.

   The URI scheme (Section 3.1) defines the namespace of the URI, and
   thus may further restrict the syntax and semantics of identifiers
   using that scheme.  This specification defines those elements of the
   URI syntax that are either required of all URI schemes or are common
   to many URI schemes.  It thus defines the syntax and semantics that
   are needed to implement a scheme-independent parsing mechanism for
   URI references, such that the scheme-dependent handling of a URI can
   be postponed until the scheme-dependent semantics are needed.  We use
   the term URL below when describing syntax or semantics that only
   apply to locators.

   Although many URL schemes are named after protocols, this does not
   imply that the only way to access the URL's resource is via the named
   protocol.  Gateways, proxies, caches, and name resolution services
   might be used to access some resources, independent of the protocol
   of their origin, and the resolution of some URL may require the use
   of more than one protocol (e.g., both DNS and HTTP are typically used
   to access an "http" URL's resource when it can't be found in a local
   cache).

**Comment by marc-portier** [comment]
Still: I find URI more ambitious :)

**Comment by pietercolpaert** [comment]
I agree with Marc

**Comment by coreation** [comment]
I vote URI as well. Maybe later on, the subset URL will become obsolete and since URL is a subset of URI, URL is still kind of "in the picture".

**Comment by pietercolpaert** [comment]
URLs won't become obsolete, it's still very interesting to use URLs for the formatters and for SPECTQL. These however don't need explicit support internally.

**Comment by coreation** [comment]
I didn't mean URLs becoming obsolete in general, but later on we might use a URI for certain reasons for a certain resource. Since I don't think URI is completely wrong, it's still useful to take it anyway for future sake.

**Comment by marc-portier** [comment]
While I have the votes on my side: http://www.w3.org/TR/uri-clarification/#contemporary

I think Lieven takes things as: "The subset of URIs that actually point to something useful for the datatank (ie downloadable resources) are the URLs so lets use that."

The more philosophical take is: resource identifiers have two functions: addressing and naming (and maybe an arguable third: identifying) - remembering this take from TBL http://www.w3.org/DesignIssues/Naming on the matter I think using URI really means that we leave the discussion open as to how people want to use this thing.

So it "means" some kind of dataset, rather then "gets" (although all cases we know about today in TDT do the latter)

**Comment by marc-portier** [comment]
Still thinking out loud: there is of course the issue of content and language negotiation to consider too.

Rather then mixing this in with the uri-url debate (because I think it is a separate issue), 
I would suggest to allow some extra (optional) parameters to go along any uri to capture these aspects.

(as you do you might want to consider injecting needed params for authentication and other request-header aspects too)

**Comment by pietercolpaert** [comment]
I agree! This is what we have been doing so far:
- ?lang=... will overwrite the accept-language header
- .json will overwrite the accept header (.about & URI always use content negotiation)

**Comment by lievenjanssen** [comment]
The URI/URL discussion we are having here is about the 'URL' pointing to a file e.g. URL to an XLS or SHP file which is clearly a representation locator instead of an identifier of an object in the real world.

But since URI is a superset of URL and I don't want to go into endless discussions let us go for URI.

**Comment by pietercolpaert** [comment]
Oh! I thought we were talking about the URIs or URLs for identifying/locating resources in The DataTank as is brought forward by the issue's subject.

@coreation - In the future, please define your issues better to avoid situations like this one.

**Comment by lievenjanssen** [comment]
Don't think we need to have a discussion about that, when we talk about identifying resources it's clearly URI.

@coreation +1 for Pieter's remark ;-)

**Comment by coreation** [comment]
What can be miss understood by URI Parameter? It's a parameter, called URI or URL. Btw, how do I blame someone? I want to blame a certain person for hard coding $format = "spectql" in the logger.

**Comment by pietercolpaert** [comment]
http://book.git-scm.com/5_finding_issues_-_git_blame.html

Feel free to fix that

**Comment by pietercolpaert** [comment]
How it can be miss-understood: there is no "parameter" in your description.

**Comment by coreation** [comment]
One of the first things I have fixed. I didn't even log an issue for that.

**Comment by coreation** [comment]
- cfr. title*

**Comment by marc-portier** [comment]
final remarks @lievenjanssen When you mention "Don't think we need to have a discussion about that, when we talk about identifying resources it's clearly URI."  I read the biggest argumentation why we should call the other side also URIs :)

Clearly it's not because we (in stead of them) are defining the resource that it can claim the more general term?
Also technically being client rather then server is not argumentation to call things locator.

**Comment by lievenjanssen** [comment]
since our generic resource types can only handle a representation of a dataset. Namely the XLS representation, CSV representation, SHP representation, ...

It still is logical for me that we don't point to a URI but to a URL because we need a specific representation of the file to be able to handle it.

Or, and now falls my euro, we need to implement the 'Accept' request header in all our strategies so we can indeed point to a URI instead of a URL.

**Comment by marc-portier** [comment]
Your argument is mixing up two things imho.
1. by naming it URL you can't guarantee that some time from now the server of the resource will not redirect, choose to deliver another contentype, or even fail (404 or other).  If you need the response to be of a certain media-type you need to check Content-type header and either dynamically switch interpretation-logic upon that or fail (with a helpful error-message :))
2. any URI can lead to the same useful sequence of bytes: suppose we (at some time) agree that http://thedatatank.org/definitions/calculated/random-test.csv "means" a set of 10 rows with 10 columns in csv format that the datatank produces by not using curl-GET, but by built-in reading 100 integers from /dev/random - then this could surely be a valid entry for a resource-definition uri-parameter, no?  Without the GET, there is no "addressing", hence no UR-Locator

**Comment by coreation** [comment]
- Fixed the url vs uri issue,
- Refactored the XLS resource,
- Refined the XLS strategy just a little: exceptions with very nice comments were thrown, but were catched at the end of the code. So there was no way this was reaching the user. 
- Updated the documentation on isValid() making it so that developers know that if they just return false, the user won't be much informed of what went wrong. Thus encouraging throwing decent exceptions during validation.
- Added a reset of the documentation after the installer had been finished making it so that back-end changes (such as a parameter uri -> url) would be included in the Doc resource immediatly instead of after an hour , or the addition of a new resource.
