### ISSUE TITLE
support type hierarchy as in resource_type = generic/CSV

### ISSUE THREAD

**Issue by marc-portier** [iRail/The-DataTank#73]
Just recreating a resource again and getting fed up with resouce_type=generic&generic_type=csv

And with the ideas about hierarchical resources recently I'm questioning if we couldn't just get the required information all from one decent parameter.

Why not semantify the resource-types, make it a URI :)

**Comment by coreation** [comment]
A very interesting idea, and probably not that hard, will let you know how this evolves. In response to your "I have to re-add my resource again, and I swear it's the same as last time" I'll probably finish the export of resources somewhere this week, making that a thing to worry less about ;). The export thing has been running through my head before our talk, because I had the same "I swear I added this resource with the same parameters, and suddenly it works." ;-)

**Comment by marc-portier** [comment]
the GET of a resource-definition in json or so would also be useful
Am I missing it or is it really not there?

-marc=

2012/4/3 Jan Vansteenlandt <
reply@reply.github.com

**Comment by coreation** [comment]
Well if you go to TDTInfo/Resource/package/resource.json .... you should get your definition in JSON .... ?

**Comment by marc-portier** [comment]
almost: I'm switching over to #48 to discuss the resrouce-definition-resource handling there

**Comment by coreation** [comment]
Implemented
